import { Amplify } from 'aws-amplify';

// This file will be auto-generated by `npx ampx sandbox` or `npx ampx pipeline-deploy`
// For now we configure manually and it gets replaced after first sandbox run
let configured = false;

export function configureAmplify() {
  if (configured) return;
  try {
    // Try to load the auto-generated config from sandbox
    const outputs = require('../amplify_outputs.json');
    Amplify.configure(outputs);
    configured = true;
  } catch {
    // amplify_outputs.json not yet generated — sandbox not running
    // Run: npx ampx sandbox
    console.warn('amplify_outputs.json not found. Run: npx ampx sandbox');
  }
}
