import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import { Amplify } from 'aws-amplify'
import App from './App'
import './index.css'

// Configure Amplify — this file is auto-generated by `npx ampx sandbox`
// Run: npx ampx sandbox  (in a separate terminal) before starting the dev server
try {
  const outputs = await import('../amplify_outputs.json')
  Amplify.configure(outputs.default)
} catch {
  console.warn(
    '⚠️  amplify_outputs.json not found.\n' +
    'Run: npx ampx sandbox\n' +
    'in a separate terminal, then refresh.'
  )
}

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>
)
